version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./src:/usr/app/src
      - ./target:/usr/app/target
#https://www.youtube.com/watch?v=5ST1f2y3HQM  how to hot reload